export enum PaymentMethodTypeEnum {
    CASH = 'CASH',
    CHECK = 'CHECK',
    DEBIT_CARD = 'DEBIT_CARD',
    CREDIT_CARD = 'CREDIT_CARD',
    PREPAID_CARD = 'PREPAID_CARD',
    VIRTUAL_CARD = 'VIRTUAL_CARD',
    BANK_TRANSFER = 'BANK_TRANSFER',
    INSTANT_TRANSFER = 'INSTANT_TRANSFER',
    DIRECT_DEBIT = 'DIRECT_DEBIT',
    WIRE_TRANSFER = 'WIRE_TRANSFER',
    E_WALLET = 'E_WALLET',
    MOBILE_WALLET = 'MOBILE_WALLET',
    MOBILE_MONEY = 'MOBILE_MONEY',
    CARRIER_BILLING = 'CARRIER_BILLING',
    QR_CODE_PAYMENT = 'QR_CODE_PAYMENT',
    BUY_NOW_PAY_LATER = 'BUY_NOW_PAY_LATER',
    INSTALLMENT_PLAN = 'INSTALLMENT_PLAN',
    CRYPTOCURRENCY = 'CRYPTOCURRENCY',
    STABLECOIN = 'STABLECOIN',
    CBDC = 'CBDC',
    LOCAL_ALTERNATIVE_PAYMENT = 'LOCAL_ALTERNATIVE_PAYMENT',
    VOUCHER = 'VOUCHER',
    CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
}

export const PAYMENT_METHOD_TYPE_LABELS: Record<PaymentMethodTypeEnum, string> = {
    [PaymentMethodTypeEnum.CASH]: "Espèces",
    [PaymentMethodTypeEnum.CHECK]: "Chèque",
    [PaymentMethodTypeEnum.DEBIT_CARD]: "Carte de débit",
    [PaymentMethodTypeEnum.CREDIT_CARD]: "Carte bancaire",
    [PaymentMethodTypeEnum.PREPAID_CARD]: "Carte prépayée",
    [PaymentMethodTypeEnum.VIRTUAL_CARD]: "Carte virtuelle",
    [PaymentMethodTypeEnum.BANK_TRANSFER]: "Virement bancaire",
    [PaymentMethodTypeEnum.INSTANT_TRANSFER]: "Transfert instantané",
    [PaymentMethodTypeEnum.DIRECT_DEBIT]: "Prélèvement",
    [PaymentMethodTypeEnum.WIRE_TRANSFER]: "Virement SWIFT",
    [PaymentMethodTypeEnum.E_WALLET]: "Portefeuille électronique",
    [PaymentMethodTypeEnum.MOBILE_WALLET]: "Portefeuille mobile",
    [PaymentMethodTypeEnum.MOBILE_MONEY]: "Mobile Money",
    [PaymentMethodTypeEnum.CARRIER_BILLING]: "Facturation opérateur",
    [PaymentMethodTypeEnum.QR_CODE_PAYMENT]: "Paiement QR Code",
    [PaymentMethodTypeEnum.BUY_NOW_PAY_LATER]: "Achetez maintenant, payez plus tard",
    [PaymentMethodTypeEnum.INSTALLMENT_PLAN]: "Paiement en plusieurs fois",
    [PaymentMethodTypeEnum.CRYPTOCURRENCY]: "Cryptomonnaie",
    [PaymentMethodTypeEnum.STABLECOIN]: "Stablecoin",
    [PaymentMethodTypeEnum.CBDC]: "MNBC",
    [PaymentMethodTypeEnum.LOCAL_ALTERNATIVE_PAYMENT]: "Paiement alternatif local",
    [PaymentMethodTypeEnum.VOUCHER]: "Bon d'achat",
    [PaymentMethodTypeEnum.CASH_ON_DELIVERY]: "Paiement à la livraison",
}

export const PAYMENT_METHOD_TYPE_OPTIONS: Array<{ value: PaymentMethodTypeEnum; label: string }> =
    Object.entries(PAYMENT_METHOD_TYPE_LABELS).map(([value, label]) => ({
        value: value as PaymentMethodTypeEnum,
        label,
    }))
