export interface CountryInterface {
  name: string;
  code: string;
  dialCode: string;
  flag: string;
}

export const countriesConstant: CountryInterface[] = [
  { name: "Afghanistan", code: "AF", dialCode: "+93", flag: "🇦🇫" },
  { name: "Albanie", code: "AL", dialCode: "+355", flag: "🇦🇱" },
  { name: "Algérie", code: "DZ", dialCode: "+213", flag: "🇩🇿" },
  { name: "Andorre", code: "AD", dialCode: "+376", flag: "🇦🇩" },
  { name: "Angola", code: "AO", dialCode: "+244", flag: "🇦🇴" },
  { name: "Antigua-et-Barbuda", code: "AG", dialCode: "+1", flag: "🇦🇬" },
  { name: "Argentine", code: "AR", dialCode: "+54", flag: "🇦🇷" },
  { name: "Arménie", code: "AM", dialCode: "+374", flag: "🇦🇲" },
  { name: "Australie", code: "AU", dialCode: "+61", flag: "🇦🇺" },
  { name: "Autriche", code: "AT", dialCode: "+43", flag: "🇦🇹" },
  { name: "Azerbaïdjan", code: "AZ", dialCode: "+994", flag: "🇦🇿" },
  { name: "Bahamas", code: "BS", dialCode: "+1", flag: "🇧🇸" },
  { name: "Bahreïn", code: "BH", dialCode: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", code: "BD", dialCode: "+880", flag: "🇧🇩" },
  { name: "Barbade", code: "BB", dialCode: "+1", flag: "🇧🇧" },
  { name: "Biélorussie", code: "BY", dialCode: "+375", flag: "🇧🇾" },
  { name: "Belgique", code: "BE", dialCode: "+32", flag: "🇧🇪" },
  { name: "Belize", code: "BZ", dialCode: "+501", flag: "🇧🇿" },
  { name: "Bénin", code: "BJ", dialCode: "+229", flag: "🇧🇯" },
  { name: "Bhoutan", code: "BT", dialCode: "+975", flag: "🇧🇹" },
  { name: "Bolivie", code: "BO", dialCode: "+591", flag: "🇧🇴" },
  { name: "Bosnie-Herzégovine", code: "BA", dialCode: "+387", flag: "🇧🇦" },
  { name: "Botswana", code: "BW", dialCode: "+267", flag: "🇧🇼" },
  { name: "Brésil", code: "BR", dialCode: "+55", flag: "🇧🇷" },
  { name: "Brunei", code: "BN", dialCode: "+673", flag: "🇧🇳" },
  { name: "Bulgarie", code: "BG", dialCode: "+359", flag: "🇧🇬" },
  { name: "Burkina Faso", code: "BF", dialCode: "+226", flag: "🇧🇫" },
  { name: "Burundi", code: "BI", dialCode: "+257", flag: "🇧🇮" },
  { name: "Cambodge", code: "KH", dialCode: "+855", flag: "🇰🇭" },
  { name: "Cameroun", code: "CM", dialCode: "+237", flag: "🇨🇲" },
  { name: "Canada", code: "CA", dialCode: "+1", flag: "🇨🇦" },
  { name: "Cap-Vert", code: "CV", dialCode: "+238", flag: "🇨🇻" },
  { name: "République centrafricaine", code: "CF", dialCode: "+236", flag: "🇨🇫" },
  { name: "Tchad", code: "TD", dialCode: "+235", flag: "🇹🇩" },
  { name: "Chili", code: "CL", dialCode: "+56", flag: "🇨🇱" },
  { name: "Chine", code: "CN", dialCode: "+86", flag: "🇨🇳" },
  { name: "Colombie", code: "CO", dialCode: "+57", flag: "🇨🇴" },
  { name: "Comores", code: "KM", dialCode: "+269", flag: "🇰🇲" },
  { name: "Congo", code: "CG", dialCode: "+242", flag: "🇨🇬" },
  { name: "Congo (RDC)", code: "CD", dialCode: "+243", flag: "🇨🇩" },
  { name: "Îles Cook", code: "CK", dialCode: "+682", flag: "🇨🇰" },
  { name: "Costa Rica", code: "CR", dialCode: "+506", flag: "🇨🇷" },
  { name: "Côte d'Ivoire", code: "CI", dialCode: "+225", flag: "🇨🇮" },
  { name: "Croatie", code: "HR", dialCode: "+385", flag: "🇭🇷" },
  { name: "Cuba", code: "CU", dialCode: "+53", flag: "🇨🇺" },
  { name: "Chypre", code: "CY", dialCode: "+357", flag: "🇨🇾" },
  { name: "Tchéquie", code: "CZ", dialCode: "+420", flag: "🇨🇿" },
  { name: "Danemark", code: "DK", dialCode: "+45", flag: "🇩🇰" },
  { name: "Djibouti", code: "DJ", dialCode: "+253", flag: "🇩🇯" },
  { name: "Dominique", code: "DM", dialCode: "+1", flag: "🇩🇲" },
  { name: "République dominicaine", code: "DO", dialCode: "+1", flag: "🇩🇴" },
  { name: "Équateur", code: "EC", dialCode: "+593", flag: "🇪🇨" },
  { name: "Égypte", code: "EG", dialCode: "+20", flag: "🇪🇬" },
  { name: "Salvador", code: "SV", dialCode: "+503", flag: "🇸🇻" },
  { name: "Guinée équatoriale", code: "GQ", dialCode: "+240", flag: "🇬🇶" },
  { name: "Érythrée", code: "ER", dialCode: "+291", flag: "🇪🇷" },
  { name: "Estonie", code: "EE", dialCode: "+372", flag: "🇪🇪" },
  { name: "Eswatini", code: "SZ", dialCode: "+268", flag: "🇸🇿" },
  { name: "Éthiopie", code: "ET", dialCode: "+251", flag: "🇪🇹" },
  { name: "Fidji", code: "FJ", dialCode: "+679", flag: "🇫🇯" },
  { name: "Finlande", code: "FI", dialCode: "+358", flag: "🇫🇮" },
  { name: "France", code: "FR", dialCode: "+33", flag: "🇫🇷" },
  { name: "Gabon", code: "GA", dialCode: "+241", flag: "🇬🇦" },
  { name: "Gambie", code: "GM", dialCode: "+220", flag: "🇬🇲" },
  { name: "Géorgie", code: "GE", dialCode: "+995", flag: "🇬🇪" },
  { name: "Allemagne", code: "DE", dialCode: "+49", flag: "🇩🇪" },
  { name: "Ghana", code: "GH", dialCode: "+233", flag: "🇬🇭" },
  { name: "Grèce", code: "GR", dialCode: "+30", flag: "🇬🇷" },
  { name: "Grenade", code: "GD", dialCode: "+1", flag: "🇬🇩" },
  { name: "Guatemala", code: "GT", dialCode: "+502", flag: "🇬🇹" },
  { name: "Guinée", code: "GN", dialCode: "+224", flag: "🇬🇳" },
  { name: "Guinée-Bissau", code: "GW", dialCode: "+245", flag: "🇬🇼" },
  { name: "Guyana", code: "GY", dialCode: "+592", flag: "🇬🇾" },
  { name: "Haïti", code: "HT", dialCode: "+509", flag: "🇭🇹" },
  { name: "Honduras", code: "HN", dialCode: "+504", flag: "🇭🇳" },
  { name: "Hongrie", code: "HU", dialCode: "+36", flag: "🇭🇺" },
  { name: "Islande", code: "IS", dialCode: "+354", flag: "🇮🇸" },
  { name: "Inde", code: "IN", dialCode: "+91", flag: "🇮🇳" },
  { name: "Indonésie", code: "ID", dialCode: "+62", flag: "🇮🇩" },
  { name: "Iran", code: "IR", dialCode: "+98", flag: "🇮🇷" },
  { name: "Irak", code: "IQ", dialCode: "+964", flag: "🇮🇶" },
  { name: "Irlande", code: "IE", dialCode: "+353", flag: "🇮🇪" },
  { name: "Israël", code: "IL", dialCode: "+972", flag: "🇮🇱" },
  { name: "Italie", code: "IT", dialCode: "+39", flag: "🇮🇹" },
  { name: "Jamaïque", code: "JM", dialCode: "+1", flag: "🇯🇲" },
  { name: "Japon", code: "JP", dialCode: "+81", flag: "🇯🇵" },
  { name: "Jordanie", code: "JO", dialCode: "+962", flag: "🇯🇴" },
  { name: "Kazakhstan", code: "KZ", dialCode: "+7", flag: "🇰🇿" },
  { name: "Kenya", code: "KE", dialCode: "+254", flag: "🇰🇪" },
  { name: "Kiribati", code: "KI", dialCode: "+686", flag: "🇰🇮" },
  { name: "Koweït", code: "KW", dialCode: "+965", flag: "🇰🇼" },
  { name: "Kirghizistan", code: "KG", dialCode: "+996", flag: "🇰🇬" },
  { name: "Laos", code: "LA", dialCode: "+856", flag: "🇱🇦" },
  { name: "Lettonie", code: "LV", dialCode: "+371", flag: "🇱🇻" },
  { name: "Liban", code: "LB", dialCode: "+961", flag: "🇱🇧" },
  { name: "Lesotho", code: "LS", dialCode: "+266", flag: "🇱🇸" },
  { name: "Liberia", code: "LR", dialCode: "+231", flag: "🇱🇷" },
  { name: "Libye", code: "LY", dialCode: "+218", flag: "🇱🇾" },
  { name: "Liechtenstein", code: "LI", dialCode: "+423", flag: "🇱🇮" },
  { name: "Lituanie", code: "LT", dialCode: "+370", flag: "🇱🇹" },
  { name: "Luxembourg", code: "LU", dialCode: "+352", flag: "🇱🇺" },
  { name: "Madagascar", code: "MG", dialCode: "+261", flag: "🇲🇬" },
  { name: "Malawi", code: "MW", dialCode: "+265", flag: "🇲🇼" },
  { name: "Malaisie", code: "MY", dialCode: "+60", flag: "🇲🇾" },
  { name: "Maldives", code: "MV", dialCode: "+960", flag: "🇲🇻" },
  { name: "Mali", code: "ML", dialCode: "+223", flag: "🇲🇱" },
  { name: "Malte", code: "MT", dialCode: "+356", flag: "🇲🇹" },
  { name: "Îles Marshall", code: "MH", dialCode: "+692", flag: "🇲🇭" },
  { name: "Mauritanie", code: "MR", dialCode: "+222", flag: "🇲🇷" },
  { name: "Maurice", code: "MU", dialCode: "+230", flag: "🇲🇺" },
  { name: "Mexique", code: "MX", dialCode: "+52", flag: "🇲🇽" },
  { name: "Micronésie", code: "FM", dialCode: "+691", flag: "🇫🇲" },
  { name: "Moldavie", code: "MD", dialCode: "+373", flag: "🇲🇩" },
  { name: "Monaco", code: "MC", dialCode: "+377", flag: "🇲🇨" },
  { name: "Mongolie", code: "MN", dialCode: "+976", flag: "🇲🇳" },
  { name: "Monténégro", code: "ME", dialCode: "+382", flag: "🇲🇪" },
  { name: "Maroc", code: "MA", dialCode: "+212", flag: "🇲🇦" },
  { name: "Mozambique", code: "MZ", dialCode: "+258", flag: "🇲🇿" },
  { name: "Myanmar", code: "MM", dialCode: "+95", flag: "🇲🇲" },
  { name: "Namibie", code: "NA", dialCode: "+264", flag: "🇳🇦" },
  { name: "Nauru", code: "NR", dialCode: "+674", flag: "🇳🇷" },
  { name: "Népal", code: "NP", dialCode: "+977", flag: "🇳🇵" },
  { name: "Pays-Bas", code: "NL", dialCode: "+31", flag: "🇳🇱" },
  { name: "Nouvelle-Zélande", code: "NZ", dialCode: "+64", flag: "🇳🇿" },
  { name: "Nicaragua", code: "NI", dialCode: "+505", flag: "🇳🇮" },
  { name: "Niger", code: "NE", dialCode: "+227", flag: "🇳🇪" },
  { name: "Nigeria", code: "NG", dialCode: "+234", flag: "🇳🇬" },
  { name: "Niue", code: "NU", dialCode: "+683", flag: "🇳🇺" },
  { name: "Corée du Nord", code: "KP", dialCode: "+850", flag: "🇰🇵" },
  { name: "Macédoine du Nord", code: "MK", dialCode: "+389", flag: "🇲🇰" },
  { name: "Norvège", code: "NO", dialCode: "+47", flag: "🇳🇴" },
  { name: "Oman", code: "OM", dialCode: "+968", flag: "🇴🇲" },
  { name: "Pakistan", code: "PK", dialCode: "+92", flag: "🇵🇰" },
  { name: "Palaos", code: "PW", dialCode: "+680", flag: "🇵🇼" },
  { name: "Palestine", code: "PS", dialCode: "+970", flag: "🇵🇸" },
  { name: "Panama", code: "PA", dialCode: "+507", flag: "🇵🇦" },
  { name: "Papouasie-Nouvelle-Guinée", code: "PG", dialCode: "+675", flag: "🇵🇬" },
  { name: "Paraguay", code: "PY", dialCode: "+595", flag: "🇵🇾" },
  { name: "Pérou", code: "PE", dialCode: "+51", flag: "🇵🇪" },
  { name: "Philippines", code: "PH", dialCode: "+63", flag: "🇵🇭" },
  { name: "Pologne", code: "PL", dialCode: "+48", flag: "🇵🇱" },
  { name: "Portugal", code: "PT", dialCode: "+351", flag: "🇵🇹" },
  { name: "Qatar", code: "QA", dialCode: "+974", flag: "🇶🇦" },
  { name: "Roumanie", code: "RO", dialCode: "+40", flag: "🇷🇴" },
  { name: "Russie", code: "RU", dialCode: "+7", flag: "🇷🇺" },
  { name: "Rwanda", code: "RW", dialCode: "+250", flag: "🇷🇼" },
  { name: "Saint-Christophe-et-Niévès", code: "KN", dialCode: "+1", flag: "🇰🇳" },
  { name: "Sainte-Lucie", code: "LC", dialCode: "+1", flag: "🇱🇨" },
  { name: "Saint-Vincent-et-les-Grenadines", code: "VC", dialCode: "+1", flag: "🇻🇨" },
  { name: "Samoa", code: "WS", dialCode: "+685", flag: "🇼🇸" },
  { name: "Saint-Marin", code: "SM", dialCode: "+378", flag: "🇸🇲" },
  { name: "Sao Tomé-et-Principe", code: "ST", dialCode: "+239", flag: "🇸🇹" },
  { name: "Arabie saoudite", code: "SA", dialCode: "+966", flag: "🇸🇦" },
  { name: "Sénégal", code: "SN", dialCode: "+221", flag: "🇸🇳" },
  { name: "Serbie", code: "RS", dialCode: "+381", flag: "🇷🇸" },
  { name: "Seychelles", code: "SC", dialCode: "+248", flag: "🇸🇨" },
  { name: "Sierra Leone", code: "SL", dialCode: "+232", flag: "🇸🇱" },
  { name: "Singapour", code: "SG", dialCode: "+65", flag: "🇸🇬" },
  { name: "Slovaquie", code: "SK", dialCode: "+421", flag: "🇸🇰" },
  { name: "Slovénie", code: "SI", dialCode: "+386", flag: "🇸🇮" },
  { name: "Îles Salomon", code: "SB", dialCode: "+677", flag: "🇸🇧" },
  { name: "Somalie", code: "SO", dialCode: "+252", flag: "🇸🇴" },
  { name: "Afrique du Sud", code: "ZA", dialCode: "+27", flag: "🇿🇦" },
  { name: "Corée du Sud", code: "KR", dialCode: "+82", flag: "🇰🇷" },
  { name: "Soudan du Sud", code: "SS", dialCode: "+211", flag: "🇸🇸" },
  { name: "Espagne", code: "ES", dialCode: "+34", flag: "🇪🇸" },
  { name: "Sri Lanka", code: "LK", dialCode: "+94", flag: "🇱🇰" },
  { name: "Soudan", code: "SD", dialCode: "+249", flag: "🇸🇩" },
  { name: "Suriname", code: "SR", dialCode: "+597", flag: "🇸🇷" },
  { name: "Suède", code: "SE", dialCode: "+46", flag: "🇸🇪" },
  { name: "Suisse", code: "CH", dialCode: "+41", flag: "🇨🇭" },
  { name: "Syrie", code: "SY", dialCode: "+963", flag: "🇸🇾" },
  { name: "Taïwan", code: "TW", dialCode: "+886", flag: "🇹🇼" },
  { name: "Tadjikistan", code: "TJ", dialCode: "+992", flag: "🇹🇯" },
  { name: "Tanzanie", code: "TZ", dialCode: "+255", flag: "🇹🇿" },
  { name: "Thaïlande", code: "TH", dialCode: "+66", flag: "🇹🇭" },
  { name: "Timor oriental", code: "TL", dialCode: "+670", flag: "🇹🇱" },
  { name: "Togo", code: "TG", dialCode: "+228", flag: "🇹🇬" },
  { name: "Tokelau", code: "TK", dialCode: "+690", flag: "🇹🇰" },
  { name: "Tonga", code: "TO", dialCode: "+676", flag: "🇹🇴" },
  { name: "Trinité-et-Tobago", code: "TT", dialCode: "+1", flag: "🇹🇹" },
  { name: "Tunisie", code: "TN", dialCode: "+216", flag: "🇹🇳" },
  { name: "Turquie", code: "TR", dialCode: "+90", flag: "🇹🇷" },
  { name: "Turkménistan", code: "TM", dialCode: "+993", flag: "🇹🇲" },
  { name: "Tuvalu", code: "TV", dialCode: "+688", flag: "🇹🇻" },
  { name: "Ouganda", code: "UG", dialCode: "+256", flag: "🇺🇬" },
  { name: "Ukraine", code: "UA", dialCode: "+380", flag: "🇺🇦" },
  { name: "Émirats arabes unis", code: "AE", dialCode: "+971", flag: "🇦🇪" },
  { name: "Royaume-Uni", code: "GB", dialCode: "+44", flag: "🇬🇧" },
  { name: "États-Unis", code: "US", dialCode: "+1", flag: "🇺🇸" },
  { name: "Uruguay", code: "UY", dialCode: "+598", flag: "🇺🇾" },
  { name: "Ouzbékistan", code: "UZ", dialCode: "+998", flag: "🇺🇿" },
  { name: "Vanuatu", code: "VU", dialCode: "+678", flag: "🇻🇺" },
  { name: "Vatican", code: "VA", dialCode: "+379", flag: "🇻🇦" },
  { name: "Venezuela", code: "VE", dialCode: "+58", flag: "🇻🇪" },
  { name: "Viêt Nam", code: "VN", dialCode: "+84", flag: "🇻🇳" },
  { name: "Yémen", code: "YE", dialCode: "+967", flag: "🇾🇪" },
  { name: "Zambie", code: "ZM", dialCode: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", code: "ZW", dialCode: "+263", flag: "🇿🇼" },
];
